FROM alpine:3.7
RUN echo "http://dl-4.alpinelinux.org/alpine/v3.7/main" >> /etc/apk/repositories && \
        echo "http://dl-4.alpinelinux.org/alpine/v3.7/community" >> /etc/apk/repositories
RUN apk update && \
        apk add python py-pip curl unzip libexif udev chromium=61.0.3163.100-r0 chromium-chromedriver=61.0.3163.100-r0 xvfb && \
        pip install selenium && \
        pip install pyvirtualdisplay
RUN apk add  unzip
RUN adduser -S unix
USER unix
COPY ./test.py /tmp/script.py
ENV DISPLAY=:0
CMD python /tmp/script.py                          
